[versions]

[libraries]
appCompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
coreKtx = { module = "androidx.core:core-ktx", version = "1.9.0" }
junit = { module = "junit:junit", version = "4.13.2" }
material = { module = "com.google.android.material:material", version = "1.8.0" }
navigationFragmentKtx = { module = "androidx.navigation:navigation-fragment-ktx", version = "2.5.3" }
navigationUiKtx = { module = "androidx.navigation:navigation-ui-ktx", version = "2.5.3" }

[bundles]
ktx = ["coreKtx", "navigationFragmentKtx", "navigationUiKtx"]

[plugins]
androidApp = { id = "com.android.application", version = "7.3.1" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version = "1.7.20" }